cloudwatch:
  config:
    namespace: learnWordsUsingPhrases
    step: PT1M
  enabled: true

telegram:
  bot:
    username: learn_words_with_phrases_bot
    token: ${TELEGRAM_BOT_TOKEN}
  notification:
    enabled: true