spring:
  profiles:
    active: local

api:
  oxford:
    app-id: ${OXFORD_API_APP_ID}
    app-key: ${OXFORD_API_APP_KEY}

cloudwatch:
  enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

logging:
  level:
    com.github.vcvitaly.learnwordsusingphrases: DEBUG

route:
  freedictionaryapi: "https://api.dictionaryapi.dev"
  oxfordapi: "https://od-api.oxforddictionaries.com"

telegram:
  bot:
    welcome-message: "Please type a word and I'll send you it's definition and an example of it's usage."
  notification:
    enabled: false
    chat-id: ${TELEGRAM_NOTIFICATION_CHAT_ID:""}