spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${TELEBOT_RDS_HOST:localhost}:${TELEBOT_DB_PORT:5432}/${TELEBOT_DB_NAME:learn_words_db}?currentSchema=${TELEBOT_DB_SCHEMA:public}
    username: ${TELEBOT_DB_USER:postgres}
    password: ${TELEBOT_DB_PASSWD:postgres}

api:
  oxford:
    app-id: ${OXFORD_API_APP_ID}
    app-key: ${OXFORD_API_APP_KEY}

cloudwatch:
  enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

logging:
  level:
    com.github.vcvitaly.learnwordsusingphrases: DEBUG

route:
  freedictionaryapi: "https://api.dictionaryapi.dev"
  oxfordapi: "https://od-api.oxforddictionaries.com"

telegram:
  notification:
    enabled: ${TELEGRAM_NOTIFICATION_ENABLED:false}
    chat-id: ${TELEGRAM_NOTIFICATION_CHAT_ID:${telegram.notification.mock-chat-id}}
    mock-chat-id: 0

app:
  service-order:
    services: ${API_SERVICE_ORDER:${app.service-order.default-order}}
    default-order: FREE_DICTIONARY;OXFORD

cache:
  caffeine:
    ttl: PT24H